language: go

services:
  - docker

env:
  - KIND_VERSION=0.3.0

before_script:
  - |
    # busybox image used in rabbitmq-ha chart timeouts on DNS resolution
    # multiple 'search' domains in resolv.conf makes it even worse
    # https://github.com/kubernetes/kubernetes/issues/66924
    sudo sed -i '/^search/ d' /etc/resolv.conf
  # Download and install KinD
  - |
    curl -fLo $HOME/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64 && chmod +x $HOME/bin/kind
    kind --version
  # Create a new Kubernetes cluster using KinD
  - |
    kind create cluster
    export KUBECONFIG="$(kind get kubeconfig-path)"
  # Download and install kubectl
  - |
    curl -fLo $HOME/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x $HOME/bin/kubectl
    kubectl version
    kubectl get pods
  # Download and install Helm
  - |
    kubectl create serviceaccount --namespace kube-system tiller
    kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
    curl -fL https://git.io/get_helm.sh | bash
    helm init --wait --service-account tiller
    helm version
  # Pull stackstorm-ha chart dependencies
  - |
    helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    helm dependency update

script:
  # Install stackstorm-ha Helm chart in CI K8s cluster
  - helm install --debug --name stackstorm-ha . --set mongodb-ha.persistentVolume.enabled=false
  # Show created K8s resources
  - kubectl get all
