language: go

services:
  - docker

env:
  - KIND_VERSION=0.3.0

jobs:
  include:
    - stage: e2e tests
      before_script:
        # Download and install kubectl
        - curl -fLo $HOME/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x $HOME/bin/kubectl
        # Download and install Helm
        - curl -fL https://git.io/get_helm.sh | bash
        # Download and install KinD
        - curl -fLo $HOME/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64 && chmod +x $HOME/bin/kind
        - |
          kubectl version
          helm version
          kind version
        # Create a new Kubernetes cluster using KinD
        - kind create cluster
        # Set KUBECONFIG environment variable
        - export KUBECONFIG="$(kind get kubeconfig-path)"
        - kubectl get pods
      script: echo 'e2e'
