apiVersion: v1
# Update StackStorm version here to rely on other Docker images tags
appVersion: 3.4dev
name: stackstorm-ha
version: 0.41.0
description: StackStorm K8s Helm Chart, optimized for running StackStorm in HA environment.
home: https://stackstorm.com/
icon: https://landscape.cncf.io/logos/stack-storm.svg
source:
  - https://github.com/stackstorm/stackstorm-ha
keywords:
  - st2
  - stackstorm
  - devops
  - SRE
  - automation
  - chatops
  - event-driven
  - auto-remediation
  - IFTTT
  - HA
maintainers:
  - name: Eugen Cusmaunsa
    email: armab@stackstorm.com
    url: https://github.com/armab
details:
  This Helm chart is a fully installable app that codifies StackStorm cluster deployment optimized for HA and K8s environment.
  RabbitMQ-HA, MongoDB-HA clusters and coordination backend st2 relies on will be deployed as 3rd party chart dependencies.
  For configuration details please check default values.yaml and README.
