dependencies:
  - name: rabbitmq-ha
    version: 1.46.1
    repository: https://charts.helm.sh/stable
    condition: rabbitmq-ha.enabled
  - name: mongodb-replicaset
    version: 3.12.0
    repository: https://charts.helm.sh/stable
    alias: mongodb-ha
    condition: mongodb-ha.enabled
  - name: external-dns
    version: 1.6.1
    repository: https://charts.helm.sh/stable
    condition: external-dns.enabled
  - name: etcd-operator
    version: 0.10.3
    repository: https://charts.helm.sh/stable
    condition: etcd-operator.enabled

