dependencies:
  - name: rabbitmq-ha
    version: 1.31.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: rabbitmq-ha.enabled
  - name: mongodb-replicaset
    version: 3.9.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    alias: mongodb-ha
    condition: mongodb-ha.enabled
  - name: docker-registry
    version: 1.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: docker-registry.enabled
  - name: kube-registry-proxy
    version: 0.3.0
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: docker-registry.enabled
  - name: external-dns
    version: 1.6.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: external-dns.enabled
  - name: etcd-operator
    version: 0.9.0
    repository: https://kubernetes-charts.storage.googleapis.com/
