version: 2
jobs:
  # Run Helm Lint checks
  helm-lint:
    working_directory: ~/stackstorm-enterprise-ha
    docker:
      - image: lachlanevenson/k8s-helm
    steps:
      - checkout
      - run:
          name: Helm Lint Check
          command: helm lint --set secrets.st2.license="123asd456fake"
      - run:
          name: Helm template
          command: helm template --set secrets.st2.license="123asd456fake" . > k8s.yaml
      - persist_to_workspace:
          root: ~/stackstorm-enterprise-ha
          paths:
            - k8s.yaml

  # Run Kubernetes lint checks
  k8s-lint:
    docker:
      - image: garethr/kubeval
    steps:
      - attach_workspace:
          at: .
      - run:
          name: K8s Kubeval Lint Check
          command: cat k8s.yaml | kubeval

workflows:
  version: 2
  helm:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint

experimental:
  notify:
    branches:
      only:
        - master
