version: 2.1

# Add additional CircleCI Orbs dependencies
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/kubernetes
  kube: circleci/kubernetes@0.3.0
  helm: circleci/helm@0.1.2

jobs:
  # Run Helm Lint checks
  helm-lint:
    working_directory: ~/stackstorm-ha
    docker:
      - image: lachlanevenson/k8s-helm
    steps:
      - checkout
      - run:
          name: Prepare Helm
          command: |
            set -x
            helm init --client-only
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
            helm dependency update
      - run:
          name: Helm Lint Check (Community)
          command: helm lint
      - run:
          name: Helm Lint Check (Enterprise)
          command: helm lint --set enterprise.enabled=true --set enterprise.license=123asd456fake
      - run:
          name: Helm template
          command: |
            mkdir -p enterprise community
            helm template --output-dir community .
            helm template --output-dir enterprise --set enterprise.enabled=true --set enterprise.license=123asd456fake .
      - persist_to_workspace:
          root: ~/stackstorm-ha/
          paths:
            - community
            - enterprise
            # TODO: Fill an issue in https://github.com/garethr/kubeval
            # 'charts' contains 3rd party templates which doesn't validate against schema due to minor 'object != null' API validation issues
            # See: https://circleci.com/gh/StackStorm/stackstorm-enterprise-ha/18
            #- charts

  # Run Kubernetes lint checks
  k8s-lint:
    docker:
      - image: garethr/kubeval
    steps:
      - attach_workspace:
          at: .
      - run:
          name: K8s Kubeval Lint Check (Community)
          command: kubeval $(find . -type f)
          working_directory: community/stackstorm-ha/templates/
      - run:
          name: K8s Kubeval Lint Check (Enterprise)
          command: kubeval $(find . -type f)
          working_directory: enterprise/stackstorm-ha/templates/

  # Spin up lightweight K8s cluster with 'KIND' and run Helm chart & e2e tests on it
  e2e:
    machine: true
    steps:
      - checkout
      - kube/install
      - helm/install-helm-client
      - run:
          name: Install K8s in Docker (KinD)
          command: sudo wget -O /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.3.0/kind-linux-amd64 && sudo chmod +x /usr/local/bin/kind
      - run:
          name: Create new K8s cluster
          command: |
            kind create cluster
            echo 'export KUBECONFIG="$(kind get kubeconfig-path)"' >> $BASH_ENV
      - helm/install-helm-on-cluster
      - run:
          name: Update Helm repo dependencies
          command: |
            helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
            helm dependency update
      - run:
          name: Resolv.conf workaround for RabbitMQ DNS issues
          command: |
            sudo sed '/^search/ d' /etc/resolv.conf
      - run:
          name: Helm install stackstorm-ha chart
          command: |
            helm install --name stackstorm-ha . \
              --set mongodb-ha.persistentVolume.enabled=false

workflows:
  version: 2
  helm:
    jobs:
      - helm-lint
      - k8s-lint:
          requires:
            - helm-lint
      - e2e:
          requires:
            - helm-lint
            - k8s-lint

experimental:
  notify:
    branches:
      only:
        - master
