---
apiVersion: v1
kind: ConfigMap
metadata:
  name: st2-pack-configs-{{ .Release.Name }}
  annotations:
    description: Custom StackStorm pack configs, shipped in '/opt/stackstorm/configs/'
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.pack_configs | indent 2 }}
