---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-st2actionrunner-post-start-script
  annotations:
    description: Custom postStart lifecycle event handler script for st2actionrunner
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  # k8s calls this script in parallel with starting st2actionrunner (ie the same time as ENTRYPOINT)
  # The pod will not be marked as "running" until this script completes successfully.
  # see: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  post-start.sh: |
    #!/bin/bash
    chown -R stanley:stanley /home/stanley/.ssh/
