{{ if .Values.st2chatops.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2chatops
  annotations: 
    description: Custom StackStorm chatops config, passed to hubot as ENV vars
  labels:
    app: st2chatops
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2chatops.env | indent 2 }}
{{ end }}
