---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2chatops
  annotations: 
    description: Custom StackStorm chatops configs, shipped in '/opt/stackstorm/chatops/'
  labels:
    app: st2chatops
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.chatops | indent 2 }}