---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-urls
  annotations:
    description: StackStorm service URLs, used across entire st2 cluster
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ST2_AUTH_URL: http://{{ .Release.Name }}-st2auth-enterprise:9100/
  ST2_API_URL: http://{{ .Release.Name }}-st2api-enterprise:9101/
  ST2_STREAM_URL: http://{{ .Release.Name }}-st2stream-enterprise:9102/
