---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-config
  annotations:
    description: Custom StackStorm config which will apply settings on top of default st2.conf
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # TODO: Bundle Docker-friendly defaults like 'host = 0.0.0.0' in original st2.conf during the Docker container build (?)
  # TODO: Bundle DB/MQ login secrets in dynamic ENV-based st2.secrets.conf, leave custom user-defined settings for st2.user.conf (?)
  # Docker/K8s-based st2 config file used for templating service names and common overrides on top of original st2.conf.
  # The order of merging: st2.conf < st2.docker.conf < st2.user.conf
  st2.docker.conf: |
    [auth]
    enable = True
    host = 0.0.0.0
    api_url = http://{{ .Release.Name }}-st2api-enterprise:9101/
    [api]
    host = 0.0.0.0
    [stream]
    host = 0.0.0.0
    [rbac]
    enable = True
    [coordination]
    url = etcd://{{ .Release.Name }}-etcd:2379
    [messaging]
    # TODO: RabbitMQ HQ connection string needs templating based on number of nodes
    url = amqp://{{ required "rabbitmq-ha.rabbitmqUsername is required!" (index .Values "rabbitmq-ha" "rabbitmqUsername") }}:{{ required "rabbitmq-ha.rabbitmqPassword is required!" (index .Values "rabbitmq-ha" "rabbitmqPassword") }}@{{ .Release.Name }}-rabbitmq-ha-discovery:5672
    [database]
    # TODO: ReplicaSet connection string needs templating based on number of MongoDB nodes
    host = mongodb://{{ .Release.Name }}-mongodb-ha/?replicaSet=rs0

  # User-defined st2 config with custom settings applied on top of everything else.
  # The order of merging: st2.conf < st2.docker.conf < st2.user.conf
  st2.user.conf: |
{{ .Values.st2.config | indent 4 }}
