---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-license
  annotations:
    description: StackStorm Enterprise license, used to authenticate to private docker.stackstorm.com Docker Hub
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  # Ensure that secret 'st2.license' is required and was really specified
  st2_license: {{ required "Secret 'st2.license' is required to pull StackStorm Enterprise images! Don't have one? Obtain 90-day free trial at https://stackstorm.com/#product" .Values.secrets.st2.license }}
  .dockerconfigjson: {{ template "imagePullSecret" . }}
