---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2auth-enterprise
  annotations:
    description: StackStorm st2auth - all authentication is managed by this service.
  labels:
    app: st2auth
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2auth
    support: enterprise
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9100

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2api-enterprise
  annotations:
    description: StackStorm st2api - service hosts the REST API endpoints that serve requests from WebUI, CLI, ChatOps and other st2 services.
  labels:
    app: st2api
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2api
    support: enterprise
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9101

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2stream-enterprise
  annotations:
    description: StackStorm st2stream - exposes a server-sent event stream, used by the clients like WebUI and ChatOps to receive update from the st2stream server.
  labels:
    app: st2stream
    tier: backend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2stream
    support: enterprise
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9102

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-st2web-enterprise
  annotations:
    description: StackStorm st2web, - an admin Web UI and main entry point for external API requests
  labels:
    app: st2web
    tier: frontend
    vendor: stackstorm
    support: enterprise
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: st2web
    support: enterprise
    release: {{ .Release.Name }}
  # TODO: Consider to template it, if needed
  type: NodePort
  ports:
  - protocol: TCP
    port: 443
